// lib/models/workout_model.dart

class Exercise {
  final String title;
  final String type; // 'timer' atau 'reps'
  final String duration; // untuk timer (contoh: '30' detik)
  final String reps; // untuk reps-based (contoh: '20' repetisi)
  final String description;
  final String imagePath;
  final String level;

  Exercise({
    required this.title,
    required this.type,
    required this.duration,
    required this.reps,
    required this.description,
    required this.imagePath,
    required this.level,
  });

  Map<String, String> toMap() {
    return {
      'title': title,
      'type': type,
      'duration': duration,
      'reps': reps,
      'description': description,
      'imagePath': imagePath,
      'level': level,
    };
  }

  factory Exercise.fromMap(Map<String, String> map) {
    return Exercise(
      title: map['title'] ?? '',
      type: map['type'] ?? 'timer',
      duration: map['duration'] ?? '30',
      reps: map['reps'] ?? '0',
      description: map['description'] ?? '',
      imagePath: map['imagePath'] ?? 'assets/images/workout2.jpg',
      level: map['level'] ?? 'Menengah',
    );
  }
}

class Workout {
  final String title;
  final String level;
  final String imagePath;
  final List<Exercise> exercises;

  Workout({
    required this.title,
    required this.level,
    required this.imagePath,
    required this.exercises,
  });
}

// Workout data dengan multiple exercises
class WorkoutData {
  static List<Workout> getAllWorkouts() {
    return [
      Workout(
        title: 'Latihan Tubuh Penuh',
        level: 'Menengah',
        imagePath: 'assets/images/high knees workout.jpg',
        exercises: [
          Exercise(
            title: 'Warm-up Jogging',
            type: 'timer',
            duration: '30',
            reps: '0',
            description: 'Mulai dengan jogging ringan untuk menghangatkan tubuh',
            imagePath: 'assets/images/high knees workout.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Push Up',
            type: 'reps',
            duration: '0',
            reps: '20',
            description: 'Push up standar untuk melatih dada, bahu, dan triceps',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Squat',
            type: 'reps',
            duration: '0',
            reps: '25',
            description: 'Squat untuk melatih kaki dan glute',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Plank Hold',
            type: 'timer',
            duration: '45',
            reps: '0',
            description: 'Tahan posisi plank untuk core strength',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Burpees',
            type: 'reps',
            duration: '0',
            reps: '15',
            description: 'Burpee untuk cardio dan full body workout',
            imagePath: 'assets/images/high knees workout.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Mountain Climber',
            type: 'timer',
            duration: '40',
            reps: '0',
            description: 'Mountain climber untuk core dan cardio',
            imagePath: 'assets/images/high knees workout.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Jumping Jack',
            type: 'reps',
            duration: '0',
            reps: '30',
            description: 'Jumping jack untuk meningkatkan detak jantung',
            imagePath: 'assets/images/high knees workout.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Dumbbell Row',
            type: 'reps',
            duration: '0',
            reps: '15',
            description: 'Baris dumbbell untuk latihan punggung dan bicep',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'High Knees',
            type: 'timer',
            duration: '35',
            reps: '0',
            description: 'High knees untuk cardio dan core',
            imagePath: 'assets/images/high knees workout.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Dumbbell Press',
            type: 'reps',
            duration: '0',
            reps: '12',
            description: 'Shoulder press dengan dumbbell',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Lunges',
            type: 'reps',
            duration: '0',
            reps: '20',
            description: 'Lunge untuk kaki dan keseimbangan',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Cool Down Stretching',
            type: 'timer',
            duration: '60',
            reps: '0',
            description: 'Pendinginan dan peregangan untuk recovery',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Menengah',
          ),
        ],
      ),
      Workout(
        title: 'Gerakan Squat',
        level: 'Menengah',
        imagePath: 'assets/images/squat Dumbbell.jpg',
        exercises: [
          Exercise(
            title: 'Warm-up Walk',
            type: 'timer',
            duration: '30',
            reps: '0',
            description: 'Berjalan santai untuk persiapan',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Bodyweight Squat',
            type: 'reps',
            duration: '0',
            reps: '25',
            description: 'Squat tanpa beban untuk teknik yang benar',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Goblet Squat',
            type: 'reps',
            duration: '0',
            reps: '20',
            description: 'Goblet squat dengan dumbbell untuk intensitas lebih',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Jump Squat',
            type: 'reps',
            duration: '0',
            reps: '15',
            description: 'Squat dengan lompatan untuk eksplosif',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Bulgarian Split Squat (L)',
            type: 'reps',
            duration: '0',
            reps: '15',
            description: 'Split squat untuk kaki kiri',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Bulgarian Split Squat (R)',
            type: 'reps',
            duration: '0',
            reps: '15',
            description: 'Split squat untuk kaki kanan',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Pistol Squat Progression',
            type: 'reps',
            duration: '0',
            reps: '8',
            description: 'Pistol squat progression exercise',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Squat Hold',
            type: 'timer',
            duration: '45',
            reps: '0',
            description: 'Tahan posisi squat untuk endurance',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Wall Sit',
            type: 'timer',
            duration: '40',
            reps: '0',
            description: 'Wall sit untuk quadriceps isometric',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Box Squat',
            type: 'reps',
            duration: '0',
            reps: '15',
            description: 'Box squat untuk kontrol dan kedalaman',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Reverse Squat Walk',
            type: 'timer',
            duration: '30',
            reps: '0',
            description: 'Squat walk ke belakang',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Cool Down Stretching',
            type: 'timer',
            duration: '60',
            reps: '0',
            description: 'Pendinginan dan peregangan kaki',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Menengah',
          ),
        ],
      ),
      Workout(
        title: 'Latihan Push Up',
        level: 'Menengah',
        imagePath: 'assets/images/Push up.jpg',
        exercises: [
          Exercise(
            title: 'Arm Circles',
            type: 'timer',
            duration: '30',
            reps: '0',
            description: 'Putaran tangan untuk warm-up',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Standard Push Up',
            type: 'reps',
            duration: '0',
            reps: '20',
            description: 'Push up standar',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Wide Grip Push Up',
            type: 'reps',
            duration: '0',
            reps: '18',
            description: 'Push up dengan grip lebar',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Diamond Push Up',
            type: 'reps',
            duration: '0',
            reps: '12',
            description: 'Diamond push up untuk triceps',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Decline Push Up',
            type: 'reps',
            duration: '0',
            reps: '12',
            description: 'Push up dengan kaki di atas untuk intensitas lebih',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Push Up Hold',
            type: 'timer',
            duration: '45',
            reps: '0',
            description: 'Tahan posisi push up (plank)',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Explosive Push Up',
            type: 'reps',
            duration: '0',
            reps: '10',
            description: 'Push up eksplosif dengan clap',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Archer Push Up',
            type: 'reps',
            duration: '0',
            reps: '12',
            description: 'Archer push up untuk satu sisi dada',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Pseudo Push Up',
            type: 'reps',
            duration: '0',
            reps: '10',
            description: 'Push up dengan gerakan yang dirancang khusus',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Incline Push Up',
            type: 'reps',
            duration: '0',
            reps: '20',
            description: 'Push up dengan tangan di atas untuk kemudahan',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Push Up Shoulder Tap',
            type: 'timer',
            duration: '35',
            reps: '0',
            description: 'Push up dengan shoulder tap',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Cool Down Stretching',
            type: 'timer',
            duration: '60',
            reps: '0',
            description: 'Pendinginan dan peregangan dada',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Menengah',
          ),
        ],
      ),
      Workout(
        title: 'Latihan Dumbbell',
        level: 'Menengah',
        imagePath: 'assets/images/latihan dumblejpg.jpg',
        exercises: [
          Exercise(
            title: 'Warm-up Rotation',
            type: 'timer',
            duration: '30',
            reps: '0',
            description: 'Rotasi tubuh untuk warm-up',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Dumbbell Curl',
            type: 'reps',
            duration: '0',
            reps: '16',
            description: 'Bicep curl dengan dumbbell',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Dumbbell Overhead Press',
            type: 'reps',
            duration: '0',
            reps: '14',
            description: 'Press dumbbell di atas kepala',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Dumbbell Row',
            type: 'reps',
            duration: '0',
            reps: '16',
            description: 'Bent over dumbbell row',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Lateral Raise',
            type: 'reps',
            duration: '0',
            reps: '15',
            description: 'Lateral dumbbell raise untuk bahu',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Dumbbell Bench Press',
            type: 'reps',
            duration: '0',
            reps: '12',
            description: 'Dumbbell bench press untuk dada',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Dumbbell Tricep Extension',
            type: 'reps',
            duration: '0',
            reps: '14',
            description: 'Tricep extension dengan dumbbell',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Goblet Hold',
            type: 'timer',
            duration: '50',
            reps: '0',
            description: 'Tahan posisi goblet',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Dumbbell Reverse Fly',
            type: 'reps',
            duration: '0',
            reps: '15',
            description: 'Reverse fly untuk posterior deltoid',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Dumbbell Squat',
            type: 'reps',
            duration: '0',
            reps: '20',
            description: 'Squat sambil memegang dumbbell',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Dumbbell Farmer Carry',
            type: 'timer',
            duration: '40',
            reps: '0',
            description: 'Berjalan sambil memegang dumbbell',
            imagePath: 'assets/images/latihan dumblejpg.jpg',
            level: 'Menengah',
          ),
          Exercise(
            title: 'Cool Down Stretching',
            type: 'timer',
            duration: '60',
            reps: '0',
            description: 'Pendinginan dan peregangan',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Menengah',
          ),
        ],
      ),
      Workout(
        title: 'Stretching Pemula',
        level: 'Pemula',
        imagePath: 'assets/images/side-plank.jpg',
        exercises: [
          Exercise(
            title: 'Neck Stretch',
            type: 'timer',
            duration: '20',
            reps: '0',
            description: 'Peregangan leher ke berbagai arah',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Shoulder Stretch',
            type: 'timer',
            duration: '25',
            reps: '0',
            description: 'Peregangan bahu',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Arm Stretch',
            type: 'timer',
            duration: '20',
            reps: '0',
            description: 'Peregangan lengan',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Chest Stretch',
            type: 'timer',
            duration: '25',
            reps: '0',
            description: 'Peregangan dada',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Back Stretch',
            type: 'timer',
            duration: '25',
            reps: '0',
            description: 'Peregangan punggung',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Side Stretch',
            type: 'timer',
            duration: '25',
            reps: '0',
            description: 'Peregangan samping tubuh',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Hamstring Stretch',
            type: 'timer',
            duration: '30',
            reps: '0',
            description: 'Peregangan hamstring',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Quad Stretch',
            type: 'timer',
            duration: '25',
            reps: '0',
            description: 'Peregangan paha depan',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Hip Stretch',
            type: 'timer',
            duration: '30',
            reps: '0',
            description: 'Peregangan pinggul',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Calf Stretch',
            type: 'timer',
            duration: '20',
            reps: '0',
            description: 'Peregangan betis',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Butterfly Stretch',
            type: 'timer',
            duration: '30',
            reps: '0',
            description: 'Peregangan kupu-kupu untuk pinggul',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
          Exercise(
            title: 'Final Relaxation',
            type: 'timer',
            duration: '60',
            reps: '0',
            description: 'Relaksasi dan pernapasan dalam',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Pemula',
          ),
        ],
      ),
      Workout(
        title: 'Cardio Lanjutan',
        level: 'Lanjutan',
        imagePath: 'assets/images/workout2.jpg',
        exercises: [
          Exercise(
            title: 'Dynamic Warm-up',
            type: 'timer',
            duration: '45',
            reps: '0',
            description: 'Dynamic stretching dan warm-up',
            imagePath: 'assets/images/workout2.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'High Intensity Intervals',
            type: 'timer',
            duration: '60',
            reps: '0',
            description: 'HIIT sprints dengan intensitas tinggi',
            imagePath: 'assets/images/high knees workout.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Jump Rope',
            type: 'timer',
            duration: '45',
            reps: '0',
            description: 'Skipping dengan kecepatan tinggi',
            imagePath: 'assets/images/workout2.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Burpee Power',
            type: 'reps',
            duration: '0',
            reps: '25',
            description: 'Burpee dengan power dan kecepatan',
            imagePath: 'assets/images/high knees workout.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Mountain Climber Sprint',
            type: 'timer',
            duration: '50',
            reps: '0',
            description: 'Mountain climber dengan kecepatan tinggi',
            imagePath: 'assets/images/high knees workout.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Box Jump',
            type: 'reps',
            duration: '0',
            reps: '15',
            description: 'Lompatan box untuk explosive power',
            imagePath: 'assets/images/workout2.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Sprint High Knees',
            type: 'timer',
            duration: '40',
            reps: '0',
            description: 'High knees dengan kecepatan sprint',
            imagePath: 'assets/images/high knees workout.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Jumping Lunges',
            type: 'reps',
            duration: '0',
            reps: '20',
            description: 'Lunge dengan lompatan',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Plyometric Push Up',
            type: 'reps',
            duration: '0',
            reps: '12',
            description: 'Push up eksplosif dengan lompatan',
            imagePath: 'assets/images/Push up.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Double Leg Hop',
            type: 'timer',
            duration: '45',
            reps: '0',
            description: 'Lompatan dua kaki dengan intensitas tinggi',
            imagePath: 'assets/images/workout2.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Jump Squat Combo',
            type: 'reps',
            duration: '0',
            reps: '18',
            description: 'Kombinasi jump squat',
            imagePath: 'assets/images/squat Dumbbell.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Cool Down Jog',
            type: 'timer',
            duration: '90',
            reps: '0',
            description: 'Jogging lambat untuk cool down dan recovery',
            imagePath: 'assets/images/workout2.jpg',
            level: 'Lanjutan',
          ),
          Exercise(
            title: 'Final Stretching',
            type: 'timer',
            duration: '60',
            reps: '0',
            description: 'Stretching untuk recovery',
            imagePath: 'assets/images/side-plank.jpg',
            level: 'Lanjutan',
          ),
        ],
      ),
    ];
  }

  static Workout? getWorkoutByTitle(String title) {
    try {
      return getAllWorkouts().firstWhere((w) => w.title == title);
    } catch (e) {
      return null;
    }
  }
}
